// Code generated by hertz generator.

package main

import (
	handler "wsm/biz/handler"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	api := r.Group("/api")
	api.GET("/imgs", handler.GetImgs)
	api.GET("/imgs/:keyword", handler.GetImgsById)
}
